### ISSUE TITLE
i upload this script but?

### ISSUE THREAD

**Issue by khaldonno** [NicolasBernier/yt2fb#1]
Hi Nicolas
i upload this script and i change a config.php
but when i run it, he head me to youtube.com

Whay?

**Comment by khaldonno** [comment]
head to https://www.youtube.com/watch?v=share&feature=youtu.be

**Comment by gulonline** [comment]
same here :(

**Comment by gulonline** [comment]
any solution please ???

**Comment by onezerocool** [comment]
same here any solution ?

**Comment by NicolasBernier** [comment]
Hi
Can you please post your config.php file here ?

**Comment by NicolasBernier** [comment]
When heading to the script without parameter, you should have a form with 2 fields, post your YouTube link in the first one and get the link to post on Facebook from the second one.

The second link should redirect to your YouTube video.

**Comment by NicolasBernier** [comment]
I just noticed the actual version I'm using differs from this one on GitHub, I've probably hotfixed it one day on the go but forgot to push it in the repo. I'll post it ASAP.

**Comment by gulonline** [comment]
waiting for your actual working version....

**Comment by NicolasBernier** [comment]
Just pushed the fixes. Please tell me guys if it works for you now :)

**Comment by onezerocool** [comment]
same its redirect me to the youtube

**Comment by NicolasBernier** [comment]
Please post your config.php here + URL to the script

**Comment by onezerocool** [comment]
<?php

/**
 * Edit this file then save it as config.php
 */

// Website configuration

define('SCRIPT_PATH', '/yfb');                     // Path to the script (without index.php)
define('SITE_URL',    'http://www.dogsaddict.com'); // Site URL, without path

// Facebook configuration

define('SITE_NAME',   'dogsaddict.com');      // Your site name
define('FB_ADMINS',   '100009860836937'); // Your Facebook profile ID

// Twitter configuration

define('TWITTER',                  '@rottweiler'); // Your Twitter usename
define('TWITTER_CARD_WHITELISTED', false);                 // Set this to true if your domain is whitelisted for video embedding
                                                           // Read https://dev.twitter.com/cards/types/player#submitting-your-card-for-approval to know more

url : www.dogsaddict.com/yfb

**Comment by onezerocool** [comment]
* Edit this file then save it as config.php
 */

// Website configuration

define('SCRIPT_PATH', '/yfb');                     // Path to the script (without index.php)
define('SITE_URL',    'http://www.dogsaddict.com'); // Site URL, without path

// Facebook configuration

define('SITE_NAME',   'dogsaddict.com');      // Your site name
define('FB_ADMINS',   '***edited****'); // Your Facebook profile ID

// Twitter configuration

define('TWITTER',                  '@rottweiler'); // Your Twitter usename
define('TWITTER_CARD_WHITELISTED', false);                 // Set this to true if your domain is whitelisted for video embedding
                                                           // Read https://dev.twitter.com/cards/types/player#submitting-your-card-for-approval to know more

url www.dogsaddict.com/yfb

**Comment by NicolasBernier** [comment]
PHP Configuration is OK, but there is something wrong with URL rewritting.
how's your .htaccess ?

**Comment by onezerocool** [comment]
you mean the main website .htaccess or   .htaccess in the script folder because i didnt find it after extract the script

**Comment by NicolasBernier** [comment]
Both of them, but there should be a .htaccess file in the yfb folder that is generated by the script.
If this file is missing, change the permissions of the yfb folder so that the scripts can write into it. 

It should look like this (If it doesn't work, try the following one) : https://pastebin.com/3UmpCD51

**Comment by onezerocool** [comment]
you mean i create .htaccess and past that code in it ?

**Comment by NicolasBernier** [comment]
This should be automatic but if your folder write permissions do not allow it, it won't work.

**Comment by onezerocool** [comment]
now i got this message   http://www.dogsaddict.com/yfb/

**Comment by onezerocool** [comment]
and the .htaccess exist because when i create the file it says file already exist

**Comment by NicolasBernier** [comment]
It is a problem with your website configuration, not the script.

**Comment by onezerocool** [comment]
ok what should i do because  i am with the support not its dedicated server

**Comment by onezerocool** [comment]
i found the .htaccess and its fine like the conf you send but still not working

**Comment by NicolasBernier** [comment]
Sorry I can't help you with that. This thread is for reporting issues with the script, not requesting support for your whole website.

**Comment by thecoderZe** [comment]
the same problem !!!!
